### ISSUE TITLE
Content Dashboard v2

### ISSUE THREAD

**Issue by carver** [ethereum/glados#260]
![Image](https://github.com/ethereum/glados/assets/4079737/085cbff4-e283-4215-a21b-afdca0c1bdff)

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/glados/issues/261
- [ ] Run duplicate checks on the same piece of data, against individual nodes that claim to be interested in the data
- [ ] Use new data from the above check to display the propagation lag time as a % of all nodes that claim to want the data
- [ ] Use new data from above as on overlay on the "best case" data, to show real data propagation vs ideal
```

The embedded chart is a sketch from a call where we talked about the ideas in the above task-list. It is an overlay of two charts:
1. A stacked area chart, showing the best case network coverage (where the stacking shows the replication factor)
2. A bar chart of actual content surveyed, with the number of unique nodes that respond with the data (an X was meant to show that no nodes are replying with the data)
