### ISSUE TITLE
Coverage Chart Ideas

### ISSUE THREAD

**Issue by carver** [ethereum/glados#267]
Brainstorm for next step issues for #261 

```[tasklist]
### Tasks
- [ ] Make bars easier to hover (wider or flip chart to vertical like https://observablehq.com/@d3/stacked-horizontal-bar-chart/2?intent=fork )
- [ ] Add a state coverage chart, once those censuses are running
- [ ] Click on bucket to navigate to chart with just that prefix, where the x-axis is just the 2nd byte of the prefix
- [ ] If there are few enough nodes, show matching Node info somewhere (hover? click?)
- [ ] Filter out nodes that have a radius that's too large?
- [ ] Split nodes into more categories, perhaps configurable with a button on the chart
- [ ] Add legend for colors
- [x] Add title
- [ ] More reliable identification of bucket in tooltip -- maybe format data somehow other than d3-recommended
- [ ] https://github.com/ethereum/glados/issues/270
```

When splitting nodes into categories, these categories seem interesting:
  - group by node make (trin, fluffy, ultralight, etc)
  - group by node make & version
  - group by team-operated fleet vs "wild" nodes
  - group by radius distance (to visually discount nodes that have huge radius)
