### ISSUE TITLE
Add Audit of BlockHeader by number

### ISSUE THREAD

**Issue by kdeme** [ethereum/glados#314]
With the addition of BlockHeader by number in the Portal network (https://github.com/ethereum/portal-network-specs/pull/334) we should be able to see its availability on the network in glados just as is done for BlockHeader by hash, block bodies and receipts.

```[tasklist]
### Tasks
- [ ] block number lookup in 4444s audit strategy
- [ ] block number lookup in Latest audit strategy
- [ ] block number lookup in Random audit strategy
```

**Comment by carver** [comment]
This has several subcomponents that could be split into different issues to work on. For example, add block number lookups to the following audit strategies:
- 4444s
- latest
- random
